//! CPU parity: the Rust reference forward vs trippy's Python forward.
//!
//! Module: `brush-pyramid` integration test `parity_cpu`
//! Purpose: prove that [`brush_pyramid::cpu::render_pyramid_cpu`] reproduces
//!     `trippy.raster.render_pyramid` on identical inputs, for all three
//!     layer-selection modes and both pixel-centre conventions. The fixtures
//!     are generated by `tools/dump_raster_fixture.py`; regenerate them with
//!
//!     PYTHONPATH=. TRIPS_DEVICE=cpu python tools/dump_raster_fixture.py
//!
//! Invariants:
//!     - Runs on any machine: no GPU, no network, milliseconds. This is what
//!       `scripts/test.sh` executes on every push.
//!     - Integer results (`n_used`, fragment counts) must match **exactly**;
//!       only the float images get a tolerance.
//! Related docs: `docs/GEOMETRY.md`; `docs/ARCHITECTURE.md`.

use brush_pyramid::cpu::render_pyramid_cpu;
use brush_pyramid::fixture::{fixture_dirs, Fixture};

/// Absolute tolerance for the feature images and `t_final`. Both sides
/// compute in float32 but accumulate in a different order (Python vectorises
/// over fragments, we loop), so the difference is rounding only — the
/// measured worst case is three orders of magnitude below this.
const TOL: f32 = 1e-4;

#[test]
fn cpu_forward_matches_python_on_every_fixture() {
    let dirs = fixture_dirs().expect("list fixtures");
    assert!(
        !dirs.is_empty(),
        "no fixtures found; run tools/dump_raster_fixture.py"
    );
    // Three modes x two pixel-centre conventions.
    assert_eq!(dirs.len(), 6, "expected 6 fixtures, found {}", dirs.len());

    for dir in dirs {
        let fixture = Fixture::load(&dir).unwrap_or_else(|e| panic!("loading {}: {e}", dir.display()));
        let got = render_pyramid_cpu(
            &fixture.points,
            &fixture.camera,
            &fixture.params,
            Some(&fixture.background),
        )
        .unwrap_or_else(|e| panic!("rendering {}: {e}", fixture.name()));

        let report = got
            .compare(&fixture.expected, TOL)
            .unwrap_or_else(|e| panic!("{}: {e}", fixture.name()));
        println!(
            "{:<34} frags={:<5} per-layer={:?} max|feature|={:.3e} max|t_final|={:.3e}",
            fixture.name(),
            got.num_fragments,
            got.fragments_per_layer,
            report.max_feature,
            report.max_t_final
        );
    }
}

#[test]
fn fixtures_exercise_both_compositing_stop_rules() {
    // A parity test that never reached `max_frags` or `t_cutoff` would pass
    // while both `break`s were broken, so assert the fixtures are actually
    // hard enough. Mirrors the clusters built by tools/dump_raster_fixture.py.
    for dir in fixture_dirs().expect("list fixtures") {
        let fixture = Fixture::load(&dir).expect("load fixture");
        let mut capped = 0usize;
        let mut cut_off = 0usize;
        for layer in &fixture.expected.layers {
            for (&used, &t) in layer.n_used.iter().zip(&layer.t_final) {
                if used == fixture.params.max_frags {
                    capped += 1;
                } else if t < fixture.params.t_cutoff {
                    cut_off += 1;
                }
            }
        }
        assert!(capped > 0, "{}: no pixel hit max_frags", fixture.name());
        assert!(cut_off > 0, "{}: no pixel hit t_cutoff", fixture.name());
    }
}

#[test]
fn every_mode_and_pixel_centre_combination_is_covered() {
    use brush_pyramid::params::{Mode, PixelCenter};
    let mut seen = Vec::new();
    for dir in fixture_dirs().expect("list fixtures") {
        let fixture = Fixture::load(&dir).expect("load fixture");
        seen.push((fixture.params.mode, fixture.params.pixel_center));
    }
    for mode in [Mode::Trilinear, Mode::Broadcast, Mode::Trips] {
        for pc in [PixelCenter::Half, PixelCenter::Integer] {
            assert!(seen.contains(&(mode, pc)), "missing fixture for {mode:?}/{pc:?}");
        }
    }
}
