#!/bin/bash
# quest_viewer_bootstrap.sh — build a self-hosted, static WebXR splat viewer bundle
# from a .sog (or .ply) using @playcanvas/splat-transform's HTML-viewer output.
# Usage: scripts/quest_viewer_bootstrap.sh [--check] [--gpu n|cpu] [--out-dir DIR] <input.sog-or-ply> <name>
# Invariants (ADR-0008-supersplat.md Stage 3, item 9):
#   - The "viewer bundle" IS @playcanvas/supersplat-viewer: splat-transform's `.html`
#     output (`--unbundled`) is generated by calling that exact npm package's
#     `renderViewerHtml`/`css`/`js` at splat-transform's own build time (verified:
#     splat-transform 3.3.3's package.json devDependency-pins
#     "@playcanvas/supersplat-viewer": "1.30.2"). Building the viewer this way,
#     instead of separately cloning+building the supersplat-viewer repo, means one
#     pinned tool (already installed by scripts/sog_export.sh) produces both the
#     .sog and the viewer, with no second build pipeline to keep in sync. Both are
#     MIT; see ADR-0008 Sec 3's licence table.
#   - Shares the SAME local, pinned, gitignored install as scripts/sog_export.sh:
#     $TRIPPY_OUTPUT/tools/splat-transform. Never a global install.
#   - `--gpu n|cpu` (default: `cpu`), same passthrough as scripts/sog_export.sh:
#     CPU is the safe default for a direct run; `--gpu 0` (or another adapter
#     index) is only ever passed from inside a scripts/gpu_submit.sh queue slot,
#     needed when building straight from a raw PLY (an already-compressed .sog
#     input is cheap either way).
#   - Output is a flat, self-contained STATIC directory (index.html, index.js,
#     index.css, settings.json, index.sog or index.compressed.ply) under
#     $TRIPPY_OUTPUT/quest-viewer/<name>/ -- exactly the "5-file ZIP" shape
#     ADR-0008 Sec 3 already documented as self-hostable. Nothing in it is served
#     yet; scripts/open_quest_viewer.sh does that.
#   - `--check` prints toolchain readiness only and exits 0 without installing or
#     building anything (same convention as scripts/sog_export.sh --check /
#     scripts/web_build.sh --check) so the CPU test suite stays offline and fast.
#   - Bash 3.2 safe, `set -u` clean.
# Related docs: docs/decisions/ADR-0008-supersplat.md Stage 3; docs/QUEST.md;
#   scripts/sog_export.sh (produces the .sog this consumes); scripts/open_quest_viewer.sh
#   (serves the bundle this produces, 127.0.0.1 by default / --lan for the Quest).
set -eu
cd "$(dirname "$0")/.."

# Kept identical to scripts/sog_export.sh's pin on purpose: one shared, idempotent
# install target, one version to bump. See that script's header for why 3.3.3.
SPLAT_TRANSFORM_PIN="3.3.3"

# Same caution line as scripts/sog_export.sh: lighter than a training job (28 GB,
# scripts/cpu_heavy.sh) but still real work if given a raw multi-GB PLY instead of
# an already-compressed .sog.
MIN_FREE_GB=10

# Exported env wins over .env (tests and worktrees set TRIPPY_OUTPUT explicitly).
_pre_env_out=${TRIPPY_OUTPUT:-}
if [ -f .env ]; then . ./.env; fi
TRIPPY_OUTPUT=${_pre_env_out:-${TRIPPY_OUTPUT:-}}
TRIPPY_OUTPUT=${TRIPPY_OUTPUT:-$PWD/output}

TOOL_DIR="$TRIPPY_OUTPUT/tools/splat-transform"
BIN="$TOOL_DIR/node_modules/.bin/splat-transform"

usage() {
  echo "usage: quest_viewer_bootstrap.sh [--check] [--gpu n|cpu] [--out-dir DIR] <input.sog-or-ply> <name>" >&2
}

_node_ok() {
  command -v node >/dev/null 2>&1 || { echo "✗ node not found on PATH" >&2; return 1; }
  ver=$(node --version | sed 's/^v//')
  major=$(printf '%s' "$ver" | cut -d. -f1)
  minor=$(printf '%s' "$ver" | cut -d. -f2)
  case "$major" in ''|*[!0-9]*) echo "✗ could not parse node --version: $ver" >&2; return 1 ;; esac
  case "$minor" in ''|*[!0-9]*) minor=0 ;; esac
  ok=0
  if [ "$major" -gt 20 ]; then ok=1; fi
  if [ "$major" -eq 20 ] && [ "$minor" -ge 19 ]; then ok=1; fi
  if [ "$ok" -ne 1 ]; then echo "✗ node $ver is older than the required 20.19" >&2; return 1; fi
  echo "node $ver OK (>= 20.19)"
  return 0
}

_freegb() {
  vm_stat | awk '/Pages free/ {f=$3} /Pages inactive/ {i=$3} /Pages speculative/ {s=$3} END {gsub("\\.","",f); gsub("\\.","",i); gsub("\\.","",s); printf "%d", (f+i+s)*16384/1073741824}'
}

_pin_installed() {
  [ -x "$BIN" ] || return 1
  # Version banner is on stderr (splat-transform quirk, confirmed empirically).
  cur=$("$BIN" -v 2>&1 | sed -n 's/^splat-transform v\([0-9.]*\).*/\1/p')
  [ "$cur" = "$SPLAT_TRANSFORM_PIN" ]
}

_ensure_splat_transform() {
  if _pin_installed; then
    echo "  splat-transform $SPLAT_TRANSFORM_PIN already installed at $TOOL_DIR"
    return 0
  fi
  mkdir -p "$TOOL_DIR"
  cat > "$TOOL_DIR/package.json" <<EOF
{
  "name": "trippy-sog-export-tool",
  "private": true,
  "description": "Local, pinned, gitignored install of @playcanvas/splat-transform for trippy's scripts/sog_export.sh and scripts/quest_viewer_bootstrap.sh. Never vendored, never global.",
  "dependencies": {
    "@playcanvas/splat-transform": "$SPLAT_TRANSFORM_PIN"
  }
}
EOF
  echo "▶ npm install (in $TOOL_DIR — a LOCAL install, not global; AGENTS.md Sec 6)"
  ( cd "$TOOL_DIR" && npm install --no-audit --no-fund )
  _pin_installed || { echo "✗ install finished but $BIN is not at $SPLAT_TRANSFORM_PIN" >&2; exit 1; }
}

# --- arg parsing ---------------------------------------------------------------
CHECK=0
OUT_DIR=""
INPUT=""
NAME=""
GPU_ARG="cpu"
while [ $# -gt 0 ]; do
  case "$1" in
    --check) CHECK=1; shift ;;
    --gpu) GPU_ARG=${2:?--gpu needs a value (an adapter index, or "cpu")}; shift 2 ;;
    --out-dir) OUT_DIR=${2:?--out-dir needs a value}; shift 2 ;;
    --) shift; break ;;
    -*) usage; exit 2 ;;
    *)
      if [ -z "$INPUT" ]; then INPUT=$1; else NAME=$1; fi
      shift
      ;;
  esac
done

if [ "$CHECK" -eq 1 ]; then
  _node_ok || exit 1
  command -v npm >/dev/null 2>&1 || { echo "✗ npm not found on PATH" >&2; exit 1; }
  echo "npm $(npm --version) OK"
  echo "free memory: $(_freegb) GB (need >= $MIN_FREE_GB GB to build)"
  if _pin_installed; then
    echo "splat-transform $SPLAT_TRANSFORM_PIN: already installed at $TOOL_DIR"
  else
    echo "splat-transform $SPLAT_TRANSFORM_PIN: would install into $TOOL_DIR (local, pinned, not global)"
  fi
  echo "would build (gpu=$GPU_ARG): <input.sog-or-ply> -> <out-dir>/<name>/index.html (+ .js/.css/.sog/settings.json)"
  exit 0
fi

[ -n "$INPUT" ] && [ -n "$NAME" ] || { usage; exit 2; }
[ -f "$INPUT" ] || { echo "✗ input not found: $INPUT" >&2; exit 2; }
INPUT_ABS=$(cd "$(dirname "$INPUT")" && pwd)/$(basename "$INPUT")

[ -n "$OUT_DIR" ] || OUT_DIR="$TRIPPY_OUTPUT/quest-viewer"
BUNDLE_DIR="$OUT_DIR/$NAME"
mkdir -p "$BUNDLE_DIR"

_node_ok
command -v npm >/dev/null 2>&1 || { echo "✗ npm not found on PATH" >&2; exit 1; }

FREEGB=$(_freegb)
[ "$FREEGB" -ge "$MIN_FREE_GB" ] || { echo "✗ only ${FREEGB} GB free; need >= $MIN_FREE_GB GB" >&2; exit 5; }
echo "free memory: ${FREEGB} GB (>= $MIN_FREE_GB GB OK)"

_ensure_splat_transform

echo "▶ building viewer bundle: $INPUT_ABS -> $BUNDLE_DIR/index.html"
"$BIN" "$INPUT_ABS" "$BUNDLE_DIR/index.html" --unbundled -g "$GPU_ARG" -w -q

for f in index.html index.js index.css settings.json; do
  [ -f "$BUNDLE_DIR/$f" ] || { echo "✗ expected $BUNDLE_DIR/$f after build, not found" >&2; exit 1; }
done
if [ ! -f "$BUNDLE_DIR/index.sog" ] && [ ! -f "$BUNDLE_DIR/index.compressed.ply" ]; then
  echo "✗ expected $BUNDLE_DIR/index.sog or index.compressed.ply after build, neither found" >&2
  exit 1
fi

echo
echo "✓ viewer bundle built at $BUNDLE_DIR"
echo
echo "sizes:"
ls -la "$BUNDLE_DIR"
echo
echo "Serve it with:"
echo "  scripts/open_quest_viewer.sh \"$BUNDLE_DIR\" \"$NAME\""
